<a href="https://colab.research.google.com/github/chatushva/ml-assignment/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Perform arithmetic operations on NumPy arrays.

In [7]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
print("addition is:",a+b)
print("subtaction is:",a-b)
print("multiplication is",a*b)
print("division is:",a/b)
print("modulus division is:",a%b)
print("exponent is:",a**b)

addition is: [3 5 7]
subtaction is: [-1 -1 -1]
multiplication is [ 2  6 12]
division is: [0.5        0.66666667 0.75      ]
modulus division is: [1 2 3]
exponent is: [ 1  8 81]


2. Write a script to compute the mean and standard deviation of a NumPy array.

2)mean<br>
In numpy mean function returns the average of the elements in array a. <br>
example:


In [11]:
x=np.array([1,2,3,4,5,6,7,8])
print("mean of array is",np.mean(x))

mean of array is 4.5


standard deviation<br>
stdev() method calculates the standard deviation from a sample of data of array. Standard deviation is a measure of how spread out the numbers are.<br>
example:

In [12]:
b=([1,2,3,4,5,6,7,8,9,10])
print("standard deviation is",np.std(b))

standard deviation is 2.8722813232690143


3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [16]:
arr=np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


4. Reshape the array into a 2x4 matrix.

In [25]:
arr=np.array([1,2,3,4,5,6,7,8])
r=arr.reshape(2,4)
print(r)

[[1 2 3 4]
 [5 6 7 8]]


5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [28]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1:,:2])
arr[arr>4]=0
print(arr)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


6. Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.

In [29]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("addition is:",a+b)
print("multiplication is:",a*b)
print("division is:",a/b)


addition is: [5 7 9]
multiplication is: [ 4 10 18]
division is: [0.25 0.4  0.5 ]


7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.

In [31]:
arr=np.random.random((4,4))
print("mean of each column is:",np.mean(arr,axis=0))
print("maximum value of the entire array is:",np.max(arr))
print("sum of all elements is:",np.sum(arr))

mean of each column is: [0.5201055  0.91938467 0.44669578 0.47283775]
maximum value of the entire array is: 0.9961369345603175
sum of all elements is: 9.436094799349192


8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [33]:
arr=np.array([1,2,3,4])
r=arr+10
print(r*2)

[22 24 26 28]


9. Perform advanced slicing and i
ndexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [45]:
arr=np.random.randint(1,100,(3,4,5))
print(arr)
print(arr[1])
second_layer = arr[1, :, :]
print("Second Layer (2D Array)", second_layer)
first_two_rows_last_three_cols = arr[:, :2,-3:]
print("\nFirst two rows and last three columns from each layer:\n", first_two_rows_last_three_cols)
arr[arr % 3 == 0] = -1
print("\nArray after replacing elements divisible by 3 with -1:\n", arr)


[[[33 35 82 91 81]
  [97  7 91 15 96]
  [ 9  6 55 75 12]
  [92 62 70 12 64]]

 [[ 5 27 74 42 16]
  [47 38 22 42 35]
  [69 56 92  1 32]
  [20 25 11  9 44]]

 [[53 52 21 18  3]
  [77 12 66 70 23]
  [59 61 68 42 66]
  [31 62 22 87 47]]]
[[ 5 27 74 42 16]
 [47 38 22 42 35]
 [69 56 92  1 32]
 [20 25 11  9 44]]
Second Layer (2D Array) [[ 5 27 74 42 16]
 [47 38 22 42 35]
 [69 56 92  1 32]
 [20 25 11  9 44]]

First two rows and last three columns from each layer:
 [[[82 91 81]
  [91 15 96]]

 [[74 42 16]
  [22 42 35]]

 [[21 18  3]
  [66 70 23]]]

Array after replacing elements divisible by 3 with -1:
 [[[-1 35 82 91 -1]
  [97  7 91 -1 -1]
  [-1 -1 55 -1 -1]
  [92 62 70 -1 64]]

 [[ 5 -1 74 -1 16]
  [47 38 22 -1 35]
  [-1 56 92  1 32]
  [20 25 11 -1 44]]

 [[53 52 -1 -1 -1]
  [77 -1 -1 70 23]
  [59 61 68 -1 -1]
  [31 62 22 -1 47]]]


10. Work with broadcasting and advanced operations in NumPy.
Create a NumPy array arr of shape (3, 3) with random integers between  
1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array.

In [50]:
arr = np.random.randint(1, 21, size=(3, 3))
print("Original Array:\n", arr)
row_means = arr.mean(axis=1, keepdims=True)
normalized_arr = arr - row_means
print("\nRow-wise Normalized Array:\n", normalized_arr)
squared_arr = np.square(arr)
print("\nSquared Array:\n", squared_arr)
top_3_indices = arr.ravel().argsort()[-3:][::-1]
top_3_values = arr.ravel()[top_3_indices]
print("\nTop 3 Maximum Values:", top_3_values)
print("Indices of Top 3 Maximum Values:", top_3_indices)

Original Array:
 [[14  9 20]
 [13 10  7]
 [10 17 10]]

Row-wise Normalized Array:
 [[-0.33333333 -5.33333333  5.66666667]
 [ 3.          0.         -3.        ]
 [-2.33333333  4.66666667 -2.33333333]]

Squared Array:
 [[196  81 400]
 [169 100  49]
 [100 289 100]]

Top 3 Maximum Values: [20 17 14]
Indices of Top 3 Maximum Values: [2 7 0]
